version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: aquacontrol-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-Lucas2012}
      POSTGRES_DB: aquacontrol
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  mqtt:
    image: eclipse-mosquitto
    container_name: aquacontrol-mqtt
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mqttdata:/mosquitto/data
      - mqttlogs:/mosquitto/log

  backend:
    build: .
    container_name: aquacontrol-backend
    restart: always
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD:-Lucas2012}@db:5432/aquacontrol
      - MQTT_URL=mqtt://mqtt:1883
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    depends_on:
      - db
      - mqtt

volumes:
  pgdata:
  mqttdata:
  mqttlogs:
